/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface_de_Cadastro;

import com.mycompany.cadastro_de_pessoas.Modelo.Pessoa;
import com.mycompany.cadastro_de_pessoas.controle.Pessoa_Controle;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno.den
 */
public class Cadastro_de_Pessoa extends javax.swing.JFrame {

    private Pessoa_Controle Pessoa_Controle = new Pessoa_Controle(); 

    public Cadastro_de_Pessoa() {
        initComponents();
    }
    
    private void preencherTabela(ArrayList<Pessoa> lista) {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tabela_de_pessoas.getModel();
        
        // Zera as linhas da tabela
        modelo.setNumRows(0); 

        // Preenche com a lista que foi passada
        for (Pessoa p : lista) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getIdade()
            });
        }
    }
    
    private void listarPessoas() {
        ArrayList<Pessoa> lista_pessoa = Pessoa_Controle.lista_de_pessoa();
        preencherTabela(lista_pessoa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_idade = new javax.swing.JTextField();
        button_cadastrar = new javax.swing.JButton();
        button_listar = new javax.swing.JButton();
        button_atualizar = new javax.swing.JButton();
        button_remover = new javax.swing.JButton();
        button_pesquisar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_busca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_de_pessoas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("CADASTRO DE PESSOA");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("NOME:");

        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("IDADE:");

        txt_idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idadeActionPerformed(evt);
            }
        });

        button_cadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        button_cadastrar.setText("CADASTRAR");
        button_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cadastrarActionPerformed(evt);
            }
        });

        button_listar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        button_listar.setText("LISTAR");
        button_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_listarActionPerformed(evt);
            }
        });

        button_atualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        button_atualizar.setText("ATUALIZAR");
        button_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_atualizarActionPerformed(evt);
            }
        });

        button_remover.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        button_remover.setText("REMOVER");
        button_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_removerActionPerformed(evt);
            }
        });

        button_pesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        button_pesquisar.setText("PESQUISAR");
        button_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pesquisarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("BUSCA:");

        txt_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscaActionPerformed(evt);
            }
        });

        tabela_de_pessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "IDADE"
            }
        ));
        tabela_de_pessoas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabela_de_pessoasAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tabela_de_pessoas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(button_pesquisar)
                        .addGap(291, 291, 291))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(256, 256, 256))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(26, 26, 26)
                                .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29)
                                .addComponent(txt_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(29, 29, 29)
                                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(button_cadastrar)
                                            .addGap(101, 101, 101))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(button_atualizar)
                                            .addGap(106, 106, 106)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(button_remover)
                                        .addComponent(button_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(115, 115, 115))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_listar)
                    .addComponent(button_cadastrar))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_atualizar)
                    .addComponent(button_remover))
                .addGap(41, 41, 41)
                .addComponent(button_pesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    private void txt_idadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idadeActionPerformed

    private void button_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cadastrarActionPerformed
        // TODO add your handling code here:
        try{
            String nome = txt_nome.getText();
            int idade = Integer.parseInt(txt_idade.getText());
            
            Pessoa_Controle.Cadastrar(nome, idade);
            JOptionPane.showMessageDialog(this, "Pessoa cadastrada com sucesso!!");
            
            txt_nome.setText("");
            txt_idade.setText("");
            
            listarPessoas();
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Insira uma idade válido!");
        }
    }//GEN-LAST:event_button_cadastrarActionPerformed

    private void button_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_listarActionPerformed
        // TODO add your handling code here:
        listarPessoas();
    }//GEN-LAST:event_button_listarActionPerformed

    private void button_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_removerActionPerformed
        // TODO add your handling code here:
        try {
            String idStr = javax.swing.JOptionPane.showInputDialog(this, "Digite o ID que deseja remover : ");
            if (idStr != null && !idStr.isEmpty()){
                int id = Integer.parseInt(idStr);
                Pessoa_Controle.remover(id);
                javax.swing.JOptionPane.showMessageDialog(this, "Pessoa removida com sucesso!");
                
                listarPessoas();
            }
        } catch (NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(this, "ID inválido");
        }
    }//GEN-LAST:event_button_removerActionPerformed

    private void button_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_atualizarActionPerformed
        // TODO add your handling code here:
        
        String nome = txt_nome.getText().trim();
        String idadeStr = txt_idade.getText().trim();
        
        if (nome.isEmpty() || idadeStr.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, Digite um novo nome e uma idade!");
            return;
        }
        
        try{
            
            int idade = Integer.parseInt(idadeStr);
            String idStr = javax.swing.JOptionPane.showInputDialog(this, "Digite o ID da pessoa que deseja atualizar: ");
            if (idStr != null && !idStr.trim().isEmpty()){
                int id = Integer.parseInt(idStr.trim());
                
                Pessoa_Controle.atualizar(id, nome, idade);
                javax.swing.JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso!");
                
                txt_nome.setText("");
                txt_idade.setText("");
                
                listarPessoas();
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro nos dados informados!!");
        }
        
    }//GEN-LAST:event_button_atualizarActionPerformed

    private void button_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pesquisarActionPerformed
        // TODO add your handling code here:
        String nome_pesquisa = txt_busca.getText().trim();
        ArrayList<Pessoa> lista = Pessoa_Controle.buscar_por_nome(nome_pesquisa);
        preencherTabela(lista);
    }//GEN-LAST:event_button_pesquisarActionPerformed

    private void txt_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscaActionPerformed

    private void tabela_de_pessoasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabela_de_pessoasAncestorAdded
        
    }//GEN-LAST:event_tabela_de_pessoasAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_de_Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_de_Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_de_Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_de_Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_de_Pessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_atualizar;
    private javax.swing.JButton button_cadastrar;
    private javax.swing.JButton button_listar;
    private javax.swing.JButton button_pesquisar;
    private javax.swing.JButton button_remover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_de_pessoas;
    private javax.swing.JTextField txt_busca;
    private javax.swing.JTextField txt_idade;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables
}